name: Push to Dockerhub

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: freonius
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            freonius/giuda:latest
